services:
  jellyclean:
    image: ghcr.io/drunkrain/jellyclean:latest
    container_name: jellyclean
    restart: unless-stopped
    ports:
      - "8095:8095"
    volumes:
      - jellyclean_data:/data
    environment:
      TZ: Europe/Paris
      JELLYCLEAN_LOG_LEVEL: INFO

volumes:
  jellyclean_data:
